{% set name = "smart_open" %}
{% set version = "6.1.0" %}
{% set sha256 = "c8fd9e9f90f0e285f1346481b0ae0fb57bd04b1138826c5e826ee98b2029d7f3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - smart_open

outputs:
   - name: smart_open
   - name: smart-open
     build:
       noarch: python
     requirements:
       host:
         - python
       run:
         - {{ pin_subpackage("smart_open", exact=True) }}

about:
  home: https://github.com/RaRe-Technologies/smart_open
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library for efficient streaming of large files

  description: |
    smart_open is a Python 3 library 
    for efficient streaming of very large files
    from/to S3, HDFS, WebHDFS or local (compressed) files. 
  dev_url: https://github.com/RaRe-Technologies/smart_open

extra:
  recipe-maintainers:
    - timkpaine
    - souravsingh
    - mpenkov
