{% set name = "smart_open" %}
{% set version = "4.1.0" %}
{% set sha256 = "26af5c1a3f2b76aab8c3200310f0fc783790ec5a231ffeec102e620acdd6262e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - boto >=2.32
    - bz2file
    - requests
    - boto3
    - google-cloud-storage

test:
  requires:
    - mock
    - responses
  imports:
    - smart_open
    - smart_open.tests

about:
  home: https://github.com/RaRe-Technologies/smart_open
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library for efficient streaming of large files

  description: |
    smart_open is a Python 3 library 
    for efficient streaming of very large files
    from/to S3, HDFS, WebHDFS or local (compressed) files. 
  dev_url: https://github.com/RaRe-Technologies/smart_open

extra:
  recipe-maintainers:
    - souravsingh
    - mpenkov
